@startuml Controller-Klasse

interface Promise<T>

package @nestjs/common {
  class "@Controller" as Controller
  hide Controller circle

  class "@Get" as Get
  hide Get circle

  class "@Req" as Req
  hide Req circle

  class "@Res" as Res
  hide Res circle

  class "@Param" as Param
  hide Param circle

  class "@Headers" as Headers
  hide Headers circle

  class "@UseInterceptors" as UseInterceptors
  hide UseInterceptors circle
}

package express {
  class Request
  class Response

  Response .[hidden].> Controller
}

package universitaet {
  package entity #FFFFFF {
    class Universitaet <<entity>>
    class Bibliothek <<entity>>
    class Kurs <<entity>>
  }

  package service {
    class UniversitaetReadService << control >>
  }

  package rest #DDDDDD {
    class UniversitaetGetController << control >> << @Controller() >> << @UseInterceptors() >> {
      + @Get() async get(@Req() req: Request, @Res() res: Response): Promise<Response<UniversitaetModel | undefined>>
      + @Get() async getById(@Param() id: number, @Req() req: Request, @Headers() version: string, @Res() res: Response): Promise<Response<UniversitaetModel | undefined>>
    }

    UniversitaetGetController o--> "1" UniversitaetReadService : service

    UniversitaetGetController ..> Controller
    UniversitaetGetController ..> Request
    UniversitaetGetController ..> Response
    UniversitaetGetController ..> Headers
    UniversitaetGetController ..> UseInterceptors
    UniversitaetGetController ..> Promise
    UniversitaetGetController .up.> UniversitaetModel
  }
}

hide empty members

footer (c) Botan Coban

@enduml
