' Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
' Copyright (C) 2019 - present Botan Coban
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.

' Preview durch <Alt>d

@startuml Controller-Klasse

package @nestjs/common {
  class "@Controller" as Controller
  hide Controller circle

  class "@Post" as Post
  hide Post circle

  class "@Req" as Req
  hide Req circle

  class "@Res" as Res
  hide Res circle

  class "@Body" as Body
  hide Body circle
}

package express {
  class Request
  class Response

  Response .[hidden].> Controller
}

package universitaet {
  package entity #FFFFFF {
    class Universitaet <<entity>>
    class Bibliothek <<entity>>
    class Kurs <<entity>>
  }

  package service {
    class UniversitaetWriteService << control >>
  }

  package rest #DDDDDD {
    class UniversitaetWriteController << control >> << @Controller() >> {
      + @Post() async post(@Body() universitaetDTO: UniversitaetDTO, @Req() req: Request, @Res() res: Response): Promise<Response>
    }

    UniversitaetWriteController o--> "1" UniversitaetWriteService : service

    UniversitaetWriteController ..> Controller
    UniversitaetWriteController ..> Request
    UniversitaetWriteController ..> Response
    UniversitaetWriteController ..> UniversitaetDTO
  }
}

hide empty members

footer (c) Botan Coban

@enduml
